"""add applications table

The applicant's school choices — the reach / match / safety portfolio — which until now lived only in
the browser, so nothing in the database could refuse a second first choice or a duplicate row.

Two constraints, and they are deliberately not each other. `UNIQUE (client_id, program_id)` says one
row per program per applicant. The partial unique index says at most one `is_primary` row per
applicant, and **the predicate is the constraint**: without its `WHERE`, a unique index on `client_id`
refuses the applicant's second program instead, and an index on `(client_id, program_id)` merely
repeats the uniqueness constraint above. Autogenerate emitted `postgresql_where` here, and the
definition was read back from `pg_indexes` after the upgrade rather than trusted to this file, because
an index that quietly lost its predicate still lets a behavioural test pass for the wrong reason.

`official_deadline` and `deadline_source_url` are nullable with no default: an official deadline
nobody has looked up is unknown, and an invented date is worse than a blank. `origin` defaults to
`user`, since a portfolio row is the applicant's own choice rather than something computed for them.
`client_id` cascades, because deleting an applicant has to take their portfolio with it — the opposite
of `task_events.application_id`, which is deliberately not a foreign key so a history entry outlives
the row it describes. That column is what this table was waiting for.

Revision ID: 03a0c19c47e1
Revises: ac5acc472c8d
Create Date: 2026-10-08 01:18:22.458998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a0c19c47e1'
down_revision: Union[str, Sequence[str], None] = 'ac5acc472c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('official_deadline', sa.Date(), nullable=True),
    sa.Column('deadline_source_url', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'program_id')
    )
    # Keep the `postgresql_where`. Dropping it turns "at most one first choice" into "at most one
    # choice", which is a different table; `tests/test_application_model.py` reads the definition back
    # from `pg_indexes` so the predicate cannot go missing quietly.
    op.create_index('uq_applications_one_primary_per_client', 'applications', ['client_id'], unique=True, postgresql_where=sa.text('is_primary'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_applications_one_primary_per_client', table_name='applications', postgresql_where=sa.text('is_primary'))
    op.drop_table('applications')
    # ### end Alembic commands ###
