"""add universities programs and prerequisites

Revision ID: 0465b9338c20
Revises: af82f144fd7d
Create Date: 2026-10-06 17:27:49.951268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0465b9338c20'
down_revision: Union[str, Sequence[str], None] = 'af82f144fd7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('university_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('degree_level', sa.String(length=32), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.String(length=32), nullable=True),
    sa.Column('minimum_mark', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('non_211_minimum_mark', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requires_cognate', sa.Boolean(), nullable=False),
    sa.Column('requires_supervisor', sa.Boolean(), nullable=False),
    sa.Column('research_proposal_required', sa.Boolean(), nullable=False),
    sa.Column('english_requirement', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('data_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_prerequisites',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_prerequisites')
    op.drop_table('programs')
    op.drop_table('universities')
    # ### end Alembic commands ###
