"""add document library and review criteria

Revision ID: 3e76566a439e
Revises: 03a0c19c47e1
Create Date: 2026-10-08 16:37:06.711451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e76566a439e'
down_revision: Union[str, Sequence[str], None] = '03a0c19c47e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('check_type', sa.String(length=16), nullable=False),
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("check_type IN ('presence', 'length', 'language', 'evidence', 'consistency')", name='ck_review_criteria_check_type'),
    sa.CheckConstraint("scope IN ('gs', 'transcript', 'cv', 'ps', 'recommendation', 'language', 'general')", name='ck_review_criteria_scope'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('program_id', sa.String(length=64), nullable=True),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('archived_by', sa.String(length=8), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IS NULL OR kind IN ('transcript', 'cv', 'ps', 'recommendation', 'language', 'passport', 'gs', 'other')", name='ck_documents_kind'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['roadmap_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_no')
    )
    # Added by hand: `documents` and `document_versions` reference each other, so autogenerate cannot
    # emit both constraints in one pass and the model declares no ORM relationship for them either.
    # SET NULL because a version is what `current_version_id` points at, and the pointer must not
    # block removing one; the document survives with no current version until the next upload.
    op.create_foreign_key(
        'fk_documents_current_version_id',
        'documents',
        'document_versions',
        ['current_version_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('document_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('overall', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("overall IN ('pass', 'needs_revision', 'insufficient_evidence')", name='ck_document_reviews_overall'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_review_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.CheckConstraint("severity IN ('info', 'warning', 'blocker')", name='ck_document_review_findings_severity'),
    sa.ForeignKeyConstraint(['criterion_id'], ['review_criteria.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['document_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_current_version_id', 'documents', type_='foreignkey')
    op.drop_table('document_review_findings')
    op.drop_table('document_reviews')
    op.drop_table('document_versions')
    op.drop_table('documents')
    op.drop_table('review_criteria')
    # ### end Alembic commands ###
