"""add roadmap phases and material templates

Revision ID: 957fa85f2d83
Revises: d80f2d2aa62d
Create Date: 2026-10-06 20:55:50.956841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957fa85f2d83'
down_revision: Union[str, Sequence[str], None] = 'd80f2d2aa62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_phases',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('offset_days', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('material_templates',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('applies_to', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['phase'], ['roadmap_phases.key'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_templates')
    op.drop_table('roadmap_phases')
    # ### end Alembic commands ###
