"""add roadmap tasks and task events

Two applicant-owned tables, and the reason a later recomputation is allowed to touch one of them
and not the other.

`roadmap_tasks` is keyed on subject, material and program together, with the empty string rather
than NULL standing for a material that is not tied to one program: a unique constraint does not
constrain NULLs, so a NULL program would let the same material be inserted twice for one applicant.
The Python-side defaults on `status`, `schedule_origin` and `origin` are the ownership rule itself —
`origin` defaults to `system` so a row the client wrote cannot claim to be a human's or the advisor's
decision by leaving the field out. `client_id` cascades, because deleting an applicant has to take
everything it owns with it.

`task_events.task_id` is deliberately **not** a foreign key. The history has to outlive the row it
describes; a foreign key here would punch a hole in the audit trail the moment a task was deleted.
`client_id` is still a foreign key with CASCADE, since an event is about a subject and there is
nothing to audit once that subject is gone.

Revision ID: ac5acc472c8d
Revises: 957fa85f2d83
Create Date: 2026-10-07 22:30:19.869416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5acc472c8d'
down_revision: Union[str, Sequence[str], None] = '957fa85f2d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=8), nullable=False),
    sa.Column('event', sa.String(length=24), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('material_key', sa.String(length=64), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('suggested_at', sa.Date(), nullable=True),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('schedule_origin', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_key'], ['material_templates.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'material_key', 'program_id')
    )
    op.create_index('ix_roadmap_tasks_client_phase', 'roadmap_tasks', ['client_id', 'phase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roadmap_tasks_client_phase', table_name='roadmap_tasks')
    op.drop_table('roadmap_tasks')
    op.drop_table('task_events')
    # ### end Alembic commands ###
