"""add clients and profiles

Revision ID: bca19bbe7770
Revises:
Create Date: 2026-10-06 16:59:09.886693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca19bbe7770'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('current_education_level', sa.String(length=32), nullable=True),
    sa.Column('school_origin', sa.String(length=16), nullable=True),
    sa.Column('school_name', sa.String(length=128), nullable=True),
    sa.Column('domestic_tier', sa.String(length=16), nullable=True),
    sa.Column('overseas_band', sa.String(length=32), nullable=True),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('gpa_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gpa_scale', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_degree_level', sa.String(length=32), nullable=True),
    sa.Column('target_field', sa.String(length=64), nullable=True),
    sa.Column('intake', sa.String(length=16), nullable=True),
    sa.Column('english_score', sa.String(length=64), nullable=True),
    sa.Column('annual_budget_cny', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('clients')
    # ### end Alembic commands ###
