'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { courses, fields, requirements, type Background } from '../../prototype-fixtures/data';
import { assessProgram, SAFETY_AVERAGE_MARGIN, REACH_AVERAGE_SHORTFALL, REACH_IELTS_SHORTFALL, type Tier } from '../../lib/prototype-tiers';
import { Heading, Sample, RequirementRows, Attribution, button, input, secondary } from './shared';
import { InstitutionPicker } from './institution-picker';
import type { ChineseInstitution } from '../../lib/prototype-library';
import { readBackground, storageKey, backgroundSummary } from './storage';
export function AssessmentForm({institutions, sources}: {institutions: {items: ChineseInstitution[]; total: number; page: number; pages: number}; sources: {source: string; url: string; tags: Record<string,string>}}) {
  const [error, setError] = useState('');
  return <><Heading title="测我能申哪些">填写你的本科背景，逐条对照示例要求。无需真实联系方式；空白信息将按“未知”处理。</Heading><form className="max-w-2xl space-y-5 rounded-2xl border border-slate-200 bg-white p-6" onSubmit={e => {
    e.preventDefault(); const form = new FormData(e.currentTarget); const number = (key: string) => { const v = String(form.get(key) ?? '').trim(); return v === '' ? null : Number(v); };
    const b: Background = { institution: String(form.get('institution') ?? ''), institutionTier: (String(form.get('tier')) || null) as Background['institutionTier'], average: number('average'), major: String(form.get('major')) || null, ielts: number('ielts') };
    try { sessionStorage.setItem(storageKey, JSON.stringify(b)); const code = new URLSearchParams(window.location.search).get('code'); window.location.assign(`/prototype/assess/result${code ? `?code=${encodeURIComponent(code)}` : ''}`); } catch { setError('当前浏览器无法保存会话背景，请允许本地会话存储后再试。'); }
  }}><p className="text-xs leading-6 text-slate-500"><Sample/> 测评依据为示例数据。测评背景仅在当前浏览器会话保存；院校搜索会向服务器查询固定名单。</p><InstitutionPicker initial={institutions} sources={sources}/><label className="block text-sm font-semibold">加权均分（百分制）<input name="average" type="number" min="0" max="100" step="0.01" placeholder="未知" className={`${input} mt-2`}/></label><label className="block text-sm font-semibold">本科专业领域 <Sample/><select name="major" defaultValue="" className={`${input} mt-2`}><option value="">未知</option>{fields.map(f => <option key={f}>{f}</option>)}<option>其他领域</option></select></label><label className="block text-sm font-semibold">雅思总分<input name="ielts" type="number" min="0" max="9" step="0.5" placeholder="未知" className={`${input} mt-2`}/></label><button className={button}>查看分档结果 →</button><p role="alert" className="text-sm text-red-700">{error}</p></form></>;
}
const groups: Tier[] = ['冲刺', '匹配', '保底', '不满足', '信息不足'];
export function AssessmentResult({skipped}: {skipped: number}) {
  const [b, setB] = useState<Background | null>(null); const [loaded, setLoaded] = useState(false); const [target, setTarget] = useState('');
  useEffect(() => { setB(readBackground()); setLoaded(true); setTarget(new URLSearchParams(window.location.search).get('code') ?? ''); }, []);
  const rows = b ? courses.map(course => { const rules = requirements(course, b.institutionTier); return { course, rules, result: assessProgram(b, rules) }; }) : [];
  return <><Heading title="你的项目分档"><Sample/> 分档基于本原型的示例要求，不代表真实招生结论。<p>仅对 {courses.length} 个有示例要求的项目分档；跳过 {skipped} 个项目：录取要求未知（待采集），不参与评分。</p></Heading><div className="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="font-semibold">分档只表示对官方要求的满足程度，不是录取概率。</p><p className="mt-2 text-sm leading-7">本页要求均为示例数据。保底：所有要求满足，均分至少高于门槛 {SAFETY_AVERAGE_MARGIN} 分；匹配：全部满足但未达到保底；冲刺：仅一项未满足，均分最多差 {REACH_AVERAGE_SHORTFALL} 分或雅思总分最多差 {REACH_IELTS_SHORTFALL}。未知项归信息不足，已知条件足以判为不满足时优先归不满足。</p></div>{!loaded ? <p>正在读取背景…</p> : !b ? <div className="rounded-xl bg-white p-6">尚未填写背景。<Link className="ml-3 text-emerald-800 underline" href="/prototype/assess">先填写背景</Link></div> : <><div className="mb-8 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">本次背景（你填写的信息）</h2><p className="my-3 text-sm leading-7">院校：{b.institution || '未知'} · 类别：{b.institutionTier ?? '未知'}<br/>均分：{b.average ?? '未知'} · 专业：{b.major ?? '未知'} · 雅思：{b.ielts ?? '未知'}</p><Link href="/prototype/assess" className={secondary}>重新填写</Link><details className="mt-4"><summary className="cursor-pointer text-sm text-emerald-800">查看可复制的背景摘要</summary><pre className="mt-3 whitespace-pre-wrap break-words text-xs leading-6">{backgroundSummary()}</pre></details></div>{groups.map(group => <section key={group} className="mb-8"><h2 className="mb-4 flex items-center gap-3 text-xl font-bold">{group} <Sample/><span className="text-sm font-normal text-slate-500">{rows.filter(r => r.result.tier === group).length} 个项目</span></h2><div className="space-y-3">{rows.filter(r => r.result.tier === group).map(({course, rules, result}) => <details key={course['CRICOS Course Code']} open={target === course['CRICOS Course Code'] || undefined} className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-semibold leading-7">{course['Course Name']}<span className="ml-3 text-xs font-normal text-slate-500">逐条查看依据 ↓</span></summary><p className="mt-3 text-xs text-slate-500">{course['Institution Name']} · CRICOS {course['CRICOS Course Code']}</p><Attribution/><RequirementRows requirements={rules} outcomes={result.outcomes}/>{result.suggestions.map(s => <p key={s} className="my-3 rounded-xl bg-emerald-50 p-4 text-sm">{s} <Sample/></p>)}<Link href={`/prototype/programs/${course['CRICOS Course Code']}`} className="text-sm text-emerald-800 underline">查看项目详情</Link></details>)}</div>{!rows.some(r => r.result.tier === group) && <p className="text-sm text-slate-500">此档暂无项目。</p>}</section>)}</>}</>;
}
