'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { courses, requirements } from '../../prototype-fixtures/data';
import { CourseCard, Heading, Attribution, Sample, button, input, secondary } from './shared';
export function Catalog() {
  const [school, setSchool] = useState(''); const [field, setField] = useState(''); const [fee, setFee] = useState(''); const [duration, setDuration] = useState(''); const [selected, setSelected] = useState<string[]>([]);
  const schools = [...new Set(courses.map(c => c['Institution Name']))]; const fields = [...new Set(courses.map(c => c['Field of Education 1 Broad Field']))];
  const results = courses.filter(c => {
    const amount = Number(c['Tuition Fee'].replace(/[^\d.]/g, ''));
    return (!school || c['Institution Name'] === school) && (!field || c['Field of Education 1 Broad Field'] === field) && (!duration || c['Duration (Weeks)'] === Number(duration)) && (!fee || (fee === 'low' ? amount < 120000 : fee === 'mid' ? amount >= 120000 && amount <= 140000 : amount > 140000));
  });
  return <><Heading title="找到适合你的项目">从真实 CRICOS 登记信息出发，了解项目的学制与总学费。录取要求另以示例演示。</Heading><section aria-label="项目筛选" className="mb-8 rounded-2xl border border-slate-200 bg-white p-5"><div className="mb-5 flex flex-wrap items-center gap-2 text-sm"><span className="mr-3 font-semibold">国家</span><button aria-pressed="true" className="rounded-lg bg-emerald-100 px-4 py-2 text-emerald-900">澳大利亚</button><button disabled className={secondary}>英国 · 即将上线</button><button disabled className={secondary}>香港 · 即将上线</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[
    ['学校', school, setSchool, schools.map(s => [s,s])], ['学科', field, setField, fields.map(f => [f,f])], ['CRICOS 登记总学费（澳元）', fee, setFee, [['low','低于 120,000'], ['mid','120,000–140,000'], ['high','高于 140,000']]], ['学制', duration, setDuration, [...new Set(courses.map(c => c['Duration (Weeks)']))].map(d => [String(d),`${d} 周`])],
  ].map(([label, value, setter, options]) => <label key={String(label)} className="text-xs font-semibold">{String(label)}<select className={`${input} mt-2`} value={value as string} onChange={e => (setter as (v: string) => void)(e.target.value)}><option value="">全部</option>{(options as string[][]).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label>)}</div><Attribution/><button className="mt-3 text-sm text-emerald-800 underline" onClick={() => { setSchool(''); setField(''); setFee(''); setDuration(''); }}>重置筛选</button></section><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">找到 {results.length} 个项目</p><div className="flex flex-wrap items-center gap-3"><span className="text-xs">已选 {selected.length}/4 · 选择 2–4 个项目</span>{selected.length >= 2 ? <Link className={button} href={`/prototype/compare?codes=${selected.join(',')}`}>开始对比 →</Link> : <button className={button} disabled>开始对比</button>}<button className="text-xs underline" onClick={() => setSelected([])}>清空选择</button></div></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{results.map(course => { const code = course['CRICOS Course Code']; return <CourseCard key={code} course={course}><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(code)} disabled={!selected.includes(code) && selected.length >= 4} onChange={e => setSelected(e.target.checked ? [...selected, code] : selected.filter(v => v !== code))}/>加入对比</label></CourseCard>; })}</div>{!results.length && <p className="rounded-xl bg-white p-8 text-center">没有符合筛选条件的项目，请调整筛选。</p>}</>;
}
export function Comparison() {
  const [codes, setCodes] = useState<string[] | null>(null);
  useEffect(() => { const raw = new URLSearchParams(window.location.search).get('codes') ?? ''; setCodes([...new Set(raw.split(',').filter(code => courses.some(c => c['CRICOS Course Code'] === code)))]); }, []);
  const selected = courses.filter(c => codes?.includes(c['CRICOS Course Code']));
  return <><Heading title="把选择放在一起">并排查看 CRICOS 事实与示例要求。<br/><Sample/> 招生要求与核验档位均为示例。</Heading>{codes === null ? <p>正在读取选择…</p> : codes.length < 2 || codes.length > 4 ? <p>请选择 2–4 个有效项目。<Link href="/prototype/programs" className="ml-2 text-emerald-800 underline">返回项目库</Link></p> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[720px] text-left text-sm"><caption className="p-4 text-left text-xs">小屏可横向滚动查看全部项目。<Attribution/></caption><thead><tr><th className="p-5">比较项目</th>{selected.map(c => <th key={c['CRICOS Course Code']} className="max-w-64 p-5 align-top"><Link className="text-emerald-800 underline" href={`/prototype/programs/${c['CRICOS Course Code']}`}>{c['Course Name']}</Link></th>)}</tr></thead><tbody>{['学校', 'CRICOS 编码', '课程层级', '学科', '学制（周）', 'CRICOS 登记总学费（澳元）', '985 均分要求', '雅思总分', '专业领域'].map((row,i) => <tr key={row} className="border-t border-slate-200"><th className="p-5 font-medium">{row}{i >= 6 && <Sample/>}</th>{selected.map(c => { const r = requirements(c); const v = [c['Institution Name'], c['CRICOS Course Code'], c['Course Level'], c['Field of Education 1 Broad Field'], c['Duration (Weeks)'], c['Tuition Fee'], r[0].value, r[1].value, r[2].value][i]; return <td className="p-5 align-top" key={c['CRICOS Course Code']}>{v ?? '未知'}{i >= 6 && <div className="mt-2"><Sample/><p className="my-2 text-xs">{r[i-6].verification} <Sample/></p><a className="text-emerald-800 underline" href="#">示例出处</a></div>}</td>; })}</tr>)}</tbody></table></div>}</>;
}
