'use client';
import { useEffect, useState } from 'react';
import { findInstitutions } from '../../app/prototype/assess/institution-search';
import { institutionTier, eligibilityNote, type ChineseInstitution } from '../../lib/prototype-library';
import { input, secondary } from './shared';
type Results = {items: ChineseInstitution[]; total: number; page: number; pages: number};
type Sources = {source: string; url: string; tags: Record<string,string>};
export function InstitutionPicker({initial, sources}: {initial: Results; sources: Sources}) {
  const [query,setQuery] = useState(''); const [page,setPage] = useState(1); const [results,setResults] = useState(initial);
  const [selected,setSelected] = useState<ChineseInstitution | null>(null); const [pending,setPending] = useState(false); const [error,setError] = useState('');
  useEffect(() => {
    let active = true;
    const timer = setTimeout(() => { setPending(true); setError(''); findInstitutions(query,String(page)).then(result => { if (active) { setResults(result); setPending(false); } }).catch(() => { if (active) {setError('搜索暂时不可用，请重试。'); setPending(false);} }); },200);
    return () => { active=false; clearTimeout(timer); };
  },[query,page]);
  const metadata = (school: ChineseInstitution) => <><p className="mt-1 text-xs">{school.province || '未知'} · {school.level || '未知'} · {school.city || '未知'}</p><div className="mt-2 flex flex-wrap gap-2">{school.tags?.map(tag => <span key={tag.tag} className="rounded bg-emerald-50 px-2 py-1 text-xs"><a className="underline" href={sources.tags[tag.tag]}>{tag.tag}</a> · {tag.verification === '待核验' ? <strong className="text-amber-800">待核验</strong> : (tag.verification || '未知')}{tag.mapping_note && <span className="block mt-1">{tag.mapping_note}</span>}</span>)}</div>{eligibilityNote(school) && <p className="mt-2 text-xs text-amber-800">{eligibilityNote(school)}</p>}</>;
  return <section aria-label="本科院校选择"><label className="block text-sm font-semibold" htmlFor="institution-search">搜索本科院校</label><input id="institution-search" className={`${input} mt-2`} maxLength={100} value={query} placeholder="输入院校名称" onChange={e => {setQuery(e.target.value);setPage(1);setPending(true);setResults({...results,items:[]});}}/><p className="mt-2 text-xs leading-6"><a className="text-emerald-800 underline" href={sources.url}>数据来源：{sources.source}</a></p><button type="button" className={`${secondary} my-3`} onClick={() => setSelected(null)}>未知 / 找不到我的学校</button><input type="hidden" name="institution" value={selected?.name || '未知'}/><input type="hidden" name="tier" value={institutionTier(selected) || ''}/><div className="mb-3 rounded-xl border border-emerald-200 p-3"><p className="font-semibold">已选院校：{selected?.name || '未知'}</p><p className="my-2 text-sm">本科院校类别（自动）：{institutionTier(selected) || '未知'}</p>{selected && metadata(selected)}</div><p role="status" className="my-2 text-xs">{error || (pending ? '正在搜索…' : `共 ${results.total} 所 · 第 ${results.page} / ${results.pages} 页`)}</p><ul className="max-h-80 space-y-2 overflow-y-auto" aria-label="院校搜索结果">{!pending && results.items.map(school => <li key={school.code} className="rounded-xl border p-3"><button type="button" className="text-left text-sm font-semibold text-emerald-900 underline" aria-pressed={selected?.code === school.code} onClick={() => setSelected(school)}>{school.name}</button>{metadata(school)}</li>)}</ul>{!pending && !results.total && <p className="text-sm">没有找到学校，请选择“未知 / 找不到我的学校”。</p>}<div className="mt-3 flex gap-3"><button type="button" className={secondary} disabled={pending || page <= 1} onClick={() => {setPending(true);setPage(page-1);}}>上一页</button><button type="button" className={secondary} disabled={pending || page >= results.pages} onClick={() => {setPending(true);setPage(page+1);}}>下一页</button></div></section>;
}
