import Link from 'next/link';
import { attribution, type Course, type Requirement } from '../../prototype-fixtures/data';
import type { Outcome } from '../../lib/prototype-tiers';
export const button = 'inline-flex items-center justify-center rounded-xl bg-emerald-800 px-5 py-3 text-sm font-semibold text-white hover:bg-emerald-900 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-emerald-700';
export const secondary = 'inline-flex items-center justify-center rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-medium hover:bg-slate-100';
export const input = 'w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 py-3 text-slate-900 focus:outline-2 focus:outline-emerald-700';
export function Sample() { return <span className="inline-block rounded-md bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-900">示例数据</span>; }
export function Attribution() { return <p className="mt-4 text-xs leading-5 text-slate-500">{attribution} · <a className="underline" href="https://data.gov.au/data/dataset/cricos">CRICOS 数据集</a> · <a className="underline" href="https://creativecommons.org/licenses/by/2.5/au/">许可</a></p>; }
export function Heading({ title, children }: { title: string; children?: React.ReactNode }) { return <div className="mb-8"><p className="mb-2 text-xs font-bold tracking-widest text-emerald-800">澳大利亚 · 留学规划</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1>{children && <div className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">{children}</div>}</div>; }
export function CourseCard({ course, children }: { course: Course; children?: React.ReactNode }) { return <article className="flex min-w-0 flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Link className="text-xs text-emerald-800 underline" href={`/prototype/schools/${course['CRICOS Provider Code']}`}>{course['Institution Name']}</Link><Link className="mt-3 text-lg font-bold leading-7 hover:text-emerald-800" href={`/prototype/programs/${course['CRICOS Course Code']}`}>{course['Course Name']}</Link><p className="mt-2 text-xs text-slate-500">CRICOS {course['CRICOS Course Code']}</p><div className="mt-5 flex flex-wrap gap-2 text-xs"><span className="rounded-lg bg-slate-100 p-2">{course['Duration (Weeks)']} 周</span><span className="rounded-lg bg-slate-100 p-2">CRICOS 登记总学费 {course['Tuition Fee']} 澳元</span></div><Attribution/><div className="mt-auto pt-4">{children}</div></article>; }
export function RequirementRows({ requirements, outcomes }: { requirements: Requirement[]; outcomes?: Outcome[] }) { return <div className="divide-y divide-slate-200">{requirements.map((r, index) => <div key={r.kind} className="grid gap-3 py-4 sm:grid-cols-[160px_1fr]"><div><p className="font-semibold">{r.label}</p><p className="mt-1 text-sm">{r.value ?? '未知'} <Sample/></p></div><div className="text-sm leading-7"><span className="mr-2 rounded-md bg-slate-100 px-2 py-1 text-xs">{r.verification}</span><Sample/>{outcomes && <p className="mt-2 font-semibold text-emerald-900">{outcomes[index].status === 'met' ? '满足' : outcomes[index].status === 'short' ? `差 ${outcomes[index].shortfall}` : outcomes[index].status === 'not-met' ? '不满足' : '未知'} <Sample/></p>}<blockquote className="mt-2 text-slate-600">“{r.quote}” <Sample/></blockquote><a href={r.source} className="text-emerald-800 underline">示例出处</a></div></div>)}</div>; }
